name: Node Continuous Integration

on: push

jobs:
  # Build Job
  build:
    name: Build and Run
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Check node version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Install node packages
        run: npm install

      - name: Run the code 
        run: node app.js